/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SPIFFS_ASSETS_FILES           2
#define MMAP_SPIFFS_ASSETS_CHECKSUM        0xB1AD

enum MMAP_SPIFFS_ASSETS_LISTS {
    MMAP_SPIFFS_ASSETS_JPG_JPG = 0,        /*!< jpg.jpg */
    MMAP_SPIFFS_ASSETS_PNG_PNG = 1,        /*!< png.png */
};
