/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_BUILD_FILES           2
#define MMAP_ASSETS_BUILD_CHECKSUM        0xB1AD

enum MMAP_ASSETS_BUILD_LISTS {
    MMAP_ASSETS_BUILD_JPG_JPG = 0,        /*!< jpg.jpg */
    MMAP_ASSETS_BUILD_PNG_PNG = 1,        /*!< png.png */
};
