#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := smart_device

EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/button
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/light
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/param
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/power_meter
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/relay
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/led
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/features/touchpad
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/platforms

include $(IDF_PATH)/make/project.mk