/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_DRIVE_B_FILES           1
#define MMAP_DRIVE_B_CHECKSUM        0xD013

enum MMAP_DRIVE_B_LISTS {
    MMAP_DRIVE_B_COLOR_B_JPG_JPG = 0,        /*!< color_B_jpg.jpg */
};
