// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: robotic_arm

#include "../ui.h"

lv_obj_t * ui_RobotGraspScreen = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_uvcframe = NULL;
lv_obj_t * ui_LogTextArea = NULL;
lv_obj_t * ui_GraspButton = NULL;
lv_obj_t * ui_GraspLabel = NULL;
lv_obj_t * ui_SyncSwitch = NULL;
lv_obj_t * ui_EnableLabel = NULL;
lv_obj_t * ui_SyncLabel = NULL;
lv_obj_t * ui_EnableSwitch = NULL;
lv_obj_t * ui_GoZeroButton = NULL;
lv_obj_t * ui_GoZeroLabel = NULL;
lv_obj_t * ui_SetZeroButton = NULL;
lv_obj_t * ui_SetZeroLabel = NULL;
// event functions

// build functions

void ui_RobotGraspScreen_screen_init(void)
{
    ui_RobotGraspScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RobotGraspScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_RobotGraspScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 640);
    lv_obj_set_height(ui_Container2, 480);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -60);
    lv_obj_set_align(ui_Container2, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uvcframe = lv_image_create(ui_Container2);
    lv_obj_set_width(ui_uvcframe, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_uvcframe, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_uvcframe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uvcframe, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_uvcframe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogTextArea = lv_textarea_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_LogTextArea, 640);
    lv_obj_set_height(ui_LogTextArea, 100);
    lv_obj_set_x(ui_LogTextArea, -190);
    lv_obj_set_y(ui_LogTextArea, 243);
    lv_obj_set_align(ui_LogTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_LogTextArea, "Placeholder...");

    ui_GraspButton = lv_button_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_GraspButton, 220);
    lv_obj_set_height(ui_GraspButton, 65);
    lv_obj_set_x(ui_GraspButton, 362);
    lv_obj_set_y(ui_GraspButton, -75);
    lv_obj_set_align(ui_GraspButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GraspButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_GraspButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GraspLabel = lv_label_create(ui_GraspButton);
    lv_obj_set_width(ui_GraspLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GraspLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GraspLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GraspLabel, "Grasp");
    lv_obj_set_style_text_font(ui_GraspLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SyncSwitch = lv_switch_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_SyncSwitch, 78);
    lv_obj_set_height(ui_SyncSwitch, 44);
    lv_obj_set_x(ui_SyncSwitch, 429);
    lv_obj_set_y(ui_SyncSwitch, -210);
    lv_obj_set_align(ui_SyncSwitch, LV_ALIGN_CENTER);

    ui_EnableLabel = lv_label_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_EnableLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnableLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EnableLabel, 290);
    lv_obj_set_y(ui_EnableLabel, -248);
    lv_obj_set_align(ui_EnableLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnableLabel, "Enable");
    lv_obj_set_style_text_font(ui_EnableLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SyncLabel = lv_label_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_SyncLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SyncLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SyncLabel, 431);
    lv_obj_set_y(ui_SyncLabel, -248);
    lv_obj_set_align(ui_SyncLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SyncLabel, "Sync");
    lv_obj_set_style_text_font(ui_SyncLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnableSwitch = lv_switch_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_EnableSwitch, 78);
    lv_obj_set_height(ui_EnableSwitch, 44);
    lv_obj_set_x(ui_EnableSwitch, 290);
    lv_obj_set_y(ui_EnableSwitch, -210);
    lv_obj_set_align(ui_EnableSwitch, LV_ALIGN_CENTER);

    ui_GoZeroButton = lv_button_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_GoZeroButton, 220);
    lv_obj_set_height(ui_GoZeroButton, 65);
    lv_obj_set_x(ui_GoZeroButton, 362);
    lv_obj_set_y(ui_GoZeroButton, 25);
    lv_obj_set_align(ui_GoZeroButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoZeroButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_GoZeroButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GoZeroLabel = lv_label_create(ui_GoZeroButton);
    lv_obj_set_width(ui_GoZeroLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GoZeroLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GoZeroLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GoZeroLabel, "Go Zero");
    lv_obj_set_style_text_font(ui_GoZeroLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetZeroButton = lv_button_create(ui_RobotGraspScreen);
    lv_obj_set_width(ui_SetZeroButton, 220);
    lv_obj_set_height(ui_SetZeroButton, 65);
    lv_obj_set_x(ui_SetZeroButton, 362);
    lv_obj_set_y(ui_SetZeroButton, 125);
    lv_obj_set_align(ui_SetZeroButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetZeroButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetZeroButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetZeroLabel = lv_label_create(ui_SetZeroButton);
    lv_obj_set_width(ui_SetZeroLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetZeroLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetZeroLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetZeroLabel, "Set Zero");
    lv_obj_set_style_text_font(ui_SetZeroLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_RobotGraspScreen_screen_destroy(void)
{
    if (ui_RobotGraspScreen) {
        lv_obj_del(ui_RobotGraspScreen);
    }

    // NULL screen variables
    ui_RobotGraspScreen = NULL;
    ui_Container2 = NULL;
    ui_uvcframe = NULL;
    ui_LogTextArea = NULL;
    ui_GraspButton = NULL;
    ui_GraspLabel = NULL;
    ui_SyncSwitch = NULL;
    ui_EnableLabel = NULL;
    ui_SyncLabel = NULL;
    ui_EnableSwitch = NULL;
    ui_GoZeroButton = NULL;
    ui_GoZeroLabel = NULL;
    ui_SetZeroButton = NULL;
    ui_SetZeroLabel = NULL;

}
