// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: robotic_arm

#ifndef UI_ROBOTGRASPSCREEN_H
#define UI_ROBOTGRASPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RobotGraspScreen
extern void ui_RobotGraspScreen_screen_init(void);
extern void ui_RobotGraspScreen_screen_destroy(void);
extern lv_obj_t * ui_RobotGraspScreen;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_uvcframe;
extern lv_obj_t * ui_LogTextArea;
extern lv_obj_t * ui_GraspButton;
extern lv_obj_t * ui_GraspLabel;
extern lv_obj_t * ui_SyncSwitch;
extern lv_obj_t * ui_EnableLabel;
extern lv_obj_t * ui_SyncLabel;
extern lv_obj_t * ui_EnableSwitch;
extern lv_obj_t * ui_GoZeroButton;
extern lv_obj_t * ui_GoZeroLabel;
extern lv_obj_t * ui_SetZeroButton;
extern lv_obj_t * ui_SetZeroLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
