/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_EAF_FILES           1
#define MMAP_EAF_CHECKSUM        0xC193

enum MMAP_EAF_LISTS {
    MMAP_EAF_EAF_TEST_EAF = 0,        /*!< eaf_test.eaf */
};
