// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: robotic_arm

#ifndef _ROBOTIC_ARM_UI_H
#define _ROBOTIC_ARM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_RobotGraspScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_panthera_grasp_init(void);
void ui_panthera_grasp_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
