#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := screen_demo

EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/i2c_devices/i2c_bus
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/i2c_devices/others
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/i2c_devices/sensor
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/features/touchpad
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/wifi/wifi_conn

include $(IDF_PATH)/make/project.mk