/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_JPG_FILES           8
#define MMAP_JPG_CHECKSUM        0xB2FE

enum MMAP_JPG_LISTS {
    MMAP_JPG_FRAME_0000_JPG = 0,        /*!< frame_0000.jpg */
    MMAP_JPG_FRAME_0001_JPG = 1,        /*!< frame_0001.jpg */
    MMAP_JPG_FRAME_0002_JPG = 2,        /*!< frame_0002.jpg */
    MMAP_JPG_FRAME_0003_JPG = 3,        /*!< frame_0003.jpg */
    MMAP_JPG_FRAME_0004_JPG = 4,        /*!< frame_0004.jpg */
    MMAP_JPG_FRAME_0005_JPG = 5,        /*!< frame_0005.jpg */
    MMAP_JPG_FRAME_0006_JPG = 6,        /*!< frame_0006.jpg */
    MMAP_JPG_FRAME_0007_JPG = 7,        /*!< frame_0007.jpg */
};
