/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SPNG_FILES           8
#define MMAP_SPNG_CHECKSUM        0x83E6

enum MMAP_SPNG_LISTS {
    MMAP_SPNG_FRAME_0000_SPNG = 0,        /*!< frame_0000.spng */
    MMAP_SPNG_FRAME_0001_SPNG = 1,        /*!< frame_0001.spng */
    MMAP_SPNG_FRAME_0002_SPNG = 2,        /*!< frame_0002.spng */
    MMAP_SPNG_FRAME_0003_SPNG = 3,        /*!< frame_0003.spng */
    MMAP_SPNG_FRAME_0004_SPNG = 4,        /*!< frame_0004.spng */
    MMAP_SPNG_FRAME_0005_SPNG = 5,        /*!< frame_0005.spng */
    MMAP_SPNG_FRAME_0006_SPNG = 6,        /*!< frame_0006.spng */
    MMAP_SPNG_FRAME_0007_SPNG = 7,        /*!< frame_0007.spng */
};
