/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SJPG_FILES           8
#define MMAP_SJPG_CHECKSUM        0x1384

enum MMAP_SJPG_LISTS {
    MMAP_SJPG_FRAME_0000_SJPG = 0,        /*!< frame_0000.sjpg */
    MMAP_SJPG_FRAME_0001_SJPG = 1,        /*!< frame_0001.sjpg */
    MMAP_SJPG_FRAME_0002_SJPG = 2,        /*!< frame_0002.sjpg */
    MMAP_SJPG_FRAME_0003_SJPG = 3,        /*!< frame_0003.sjpg */
    MMAP_SJPG_FRAME_0004_SJPG = 4,        /*!< frame_0004.sjpg */
    MMAP_SJPG_FRAME_0005_SJPG = 5,        /*!< frame_0005.sjpg */
    MMAP_SJPG_FRAME_0006_SJPG = 6,        /*!< frame_0006.sjpg */
    MMAP_SJPG_FRAME_0007_SJPG = 7,        /*!< frame_0007.sjpg */
};
