/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_PNG_FILES           8
#define MMAP_PNG_CHECKSUM        0x8DA2

enum MMAP_PNG_LISTS {
    MMAP_PNG_FRAME_0000_PNG = 0,        /*!< frame_0000.png */
    MMAP_PNG_FRAME_0001_PNG = 1,        /*!< frame_0001.png */
    MMAP_PNG_FRAME_0002_PNG = 2,        /*!< frame_0002.png */
    MMAP_PNG_FRAME_0003_PNG = 3,        /*!< frame_0003.png */
    MMAP_PNG_FRAME_0004_PNG = 4,        /*!< frame_0004.png */
    MMAP_PNG_FRAME_0005_PNG = 5,        /*!< frame_0005.png */
    MMAP_PNG_FRAME_0006_PNG = 6,        /*!< frame_0006.png */
    MMAP_PNG_FRAME_0007_PNG = 7,        /*!< frame_0007.png */
};
