/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SQOI_FILES           8
#define MMAP_SQOI_CHECKSUM        0x9626

enum MMAP_SQOI_LISTS {
    MMAP_SQOI_FRAME_0000_SQOI = 0,        /*!< frame_0000.sqoi */
    MMAP_SQOI_FRAME_0001_SQOI = 1,        /*!< frame_0001.sqoi */
    MMAP_SQOI_FRAME_0002_SQOI = 2,        /*!< frame_0002.sqoi */
    MMAP_SQOI_FRAME_0003_SQOI = 3,        /*!< frame_0003.sqoi */
    MMAP_SQOI_FRAME_0004_SQOI = 4,        /*!< frame_0004.sqoi */
    MMAP_SQOI_FRAME_0005_SQOI = 5,        /*!< frame_0005.sqoi */
    MMAP_SQOI_FRAME_0006_SQOI = 6,        /*!< frame_0006.sqoi */
    MMAP_SQOI_FRAME_0007_SQOI = 7,        /*!< frame_0007.sqoi */
};
