/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_QOI_FILES           8
#define MMAP_QOI_CHECKSUM        0x7205

enum MMAP_QOI_LISTS {
    MMAP_QOI_FRAME_0000_QOI = 0,        /*!< frame_0000.qoi */
    MMAP_QOI_FRAME_0001_QOI = 1,        /*!< frame_0001.qoi */
    MMAP_QOI_FRAME_0002_QOI = 2,        /*!< frame_0002.qoi */
    MMAP_QOI_FRAME_0003_QOI = 3,        /*!< frame_0003.qoi */
    MMAP_QOI_FRAME_0004_QOI = 4,        /*!< frame_0004.qoi */
    MMAP_QOI_FRAME_0005_QOI = 5,        /*!< frame_0005.qoi */
    MMAP_QOI_FRAME_0006_QOI = 6,        /*!< frame_0006.qoi */
    MMAP_QOI_FRAME_0007_QOI = 7,        /*!< frame_0007.qoi */
};
