/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define TOTAL_MMAP_FILES      3
#define MMAP_CHECKSUM         0x2371

enum MMAP_FILES {
    MMAP_LIGHT_ICON_SPNG = 0,   /*!< light_icon.spng */
    MMAP_TEMP_ICON_SPNG = 1,   /*!< temp_icon.spng */
    MMAP_WASH_ICON_SPNG = 2,   /*!< wash_icon.spng */
};
