// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL; lv_obj_t *ui_CamImage = NULL; lv_obj_t *ui_ClassRoller = NULL; lv_obj_t *ui_RecordButton = NULL; lv_obj_t *ui_RecordLabel = NULL; lv_obj_t *ui_RecogButton = NULL; lv_obj_t *ui_RecogLabl = NULL; lv_obj_t *ui_SelectLabel = NULL;
// event functions

// build functions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CamImage = lv_image_create(ui_Screen1);
    lv_obj_set_width(ui_CamImage, 640);
    lv_obj_set_height(ui_CamImage, 480);
    lv_obj_set_x(ui_CamImage, -195);
    lv_obj_set_y(ui_CamImage, -117);
    lv_obj_set_align(ui_CamImage, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_CamImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_CamImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClassRoller = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_ClassRoller, "Class 0\nClass 1\nClass 2\nClass 3\nClass 4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_ClassRoller, 150);
    lv_obj_set_height(ui_ClassRoller, 94);
    lv_obj_set_x(ui_ClassRoller, 423);
    lv_obj_set_y(ui_ClassRoller, -219);
    lv_obj_set_align(ui_ClassRoller, LV_ALIGN_CENTER);

    ui_RecordButton = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_RecordButton, 150);
    lv_obj_set_height(ui_RecordButton, 94);
    lv_obj_set_x(ui_RecordButton, 231);
    lv_obj_set_y(ui_RecordButton, -72);
    lv_obj_set_align(ui_RecordButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecordButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RecordButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecordLabel = lv_label_create(ui_RecordButton);
    lv_obj_set_width(ui_RecordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordLabel, 0);
    lv_obj_set_y(ui_RecordLabel, -1);
    lv_obj_set_align(ui_RecordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordLabel, "Record");
    lv_obj_set_style_text_font(ui_RecordLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecogButton = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_RecogButton, 150);
    lv_obj_set_height(ui_RecogButton, 94);
    lv_obj_set_x(ui_RecogButton, 423);
    lv_obj_set_y(ui_RecogButton, -71);
    lv_obj_set_align(ui_RecogButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecogButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RecogButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecogLabl = lv_label_create(ui_RecogButton);
    lv_obj_set_width(ui_RecogLabl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecogLabl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecogLabl, 0);
    lv_obj_set_y(ui_RecogLabl, -1);
    lv_obj_set_align(ui_RecogLabl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecogLabl, "Recog");
    lv_obj_set_style_text_font(ui_RecogLabl, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SelectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectLabel, 233);
    lv_obj_set_y(ui_SelectLabel, -212);
    lv_obj_set_align(ui_SelectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectLabel, "Select Class");
    lv_obj_set_style_text_font(ui_SelectLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1) {
        lv_obj_del(ui_Screen1);
    }

// NULL screen variables
    ui_Screen1 = NULL;
    ui_CamImage = NULL;
    ui_ClassRoller = NULL;
    ui_RecordButton = NULL;
    ui_RecordLabel = NULL;
    ui_RecogButton = NULL;
    ui_RecogLabl = NULL;
    ui_SelectLabel = NULL;

}
