// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_CamImage;
extern lv_obj_t *ui_ClassRoller;
extern lv_obj_t *ui_RecordButton;
extern lv_obj_t *ui_RecordLabel;
extern lv_obj_t *ui_RecogButton;
extern lv_obj_t *ui_RecogLabl;
extern lv_obj_t *ui_SelectLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
