/*
 * SPDX-FileCopyrightText: 2024-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <string.h>

#include "FreeRTOS_CLI.h"

#include "data_back.h"

/* Dimensions the buffer into which input characters are placed. */
#define cmdMAX_INPUT_SIZE   80

/* Dimensions the buffer into which string outputs can be placed. */
#define cmdMAX_OUTPUT_SIZE  1024

void Command_Parse(char* Cmd)
{
    size_t lBytes, lByte;
    signed char cInChar;
    static signed char cInputIndex = 0;
    static char cInputString[ cmdMAX_INPUT_SIZE ], cOutputString[ cmdMAX_OUTPUT_SIZE ];
    BaseType_t xMoreDataToFollow;

    lBytes = strlen(Cmd);

    /* Process each received byte in turn. */
    lByte = 0;
    while (lByte < lBytes) {
        /* The next character in the input buffer. */
        cInChar = Cmd[ lByte ];
        lByte++;

        /* Newline characters are taken as the end of the command string. */
        if (cInChar == '\n') {
            esp_data_back("\r\n", sizeof("\r\n") - 1, ENABLE_FLUSH);
            /* Process the input string received prior to the newline. */
            do {
                /* Pass the string to FreeRTOS+CLI. */
                xMoreDataToFollow = FreeRTOS_CLIProcessCommand(cInputString, cOutputString, cmdMAX_OUTPUT_SIZE);
                /* Send the output generated by the command's implementation. */
                esp_data_back(cOutputString, strlen(cOutputString), DISABLE_FLUSH);
            } while (xMoreDataToFollow != pdFALSE);  /* Until the command does not generate any more output. */

            /* All the strings generated by the command processing have been sent.
            Clear the input string ready to receive the next command. */
            esp_data_back(">", sizeof(">") - 1, ENABLE_FLUSH);
            cInputIndex = 0;
            memset(cInputString, 0x00, cmdMAX_INPUT_SIZE);
        } else {
            if (cInChar == '\r') {
                /* Ignore the character.  Newlines are used to detect the end of the input string. */
            } else if (cInChar == '\b') {
                /* Backspace was pressed.  Erase the last character in the string - if any. */
                if (cInputIndex > 0) {
                    cInputIndex--;
                    cInputString[ cInputIndex ] = '\0';
                }
            } else {
                /* A character was entered.  Add it to the string entered so far.
                When a \n is entered the complete string will be passed to the command interpreter.*/
                if (cInputIndex < cmdMAX_INPUT_SIZE - 1) {
                    cInputString[ cInputIndex ] = cInChar;
                    cInputIndex++;
                }
            }
        }
    }
}
