# Note: All operators are binary operators. For more than two operands, you may use the nested parentheses trick.
# For example:
#    *  A == 1 or (B == 2 and C in [1,2,3])
#    *  (A == 1 and B == 2) or (C not in ["3", "4", 5])

examples/audio/wav_player:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/bluetooth/ble_conn_mgr/ble_periodic_adv:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_conn_mgr/ble_periodic_sync:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_conn_mgr/ble_spp/spp_client:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)
examples/bluetooth/ble_conn_mgr/ble_spp/spp_server:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_profiles/ble_anp:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_profiles/ble_hrp:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_profiles/ble_htp:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_ans:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_bas:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_bcs:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_cts:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_dis:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_hrs:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_hts:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_tps:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_uds:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_services/ble_wss:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 3)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c2","esp32c3","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_ota:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c3","esp32s3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32c3","esp32s3","esp32c2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32","esp32c3","esp32s3","esp32c2","esp32c6","esp32h2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/bluetooth/ble_remote_control:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"]

examples/camera/basic:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/camera/pic_server:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/camera/pic_server:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/camera/test_framerate:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/camera/video_recorder:
  enable:
    - if: IDF_TARGET == "esp32s3"

examples/camera/video_stream_server:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)

examples/check_pedestrian_flow:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/display/lcd/qspi_with_ram:
  enable:
    - if: IDF_TARGET in ["esp32","esp32c2","esp32c3","esp32c6","esp32h2","esp32s2", "esp32s3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/display/lcd/qspi_without_ram:
  enable:
    - if: IDF_TARGET in ["esp32s3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 3)

examples/display/lcd/rgb_lcd_8bit:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

examples/display/lcd/rgb_avoid_tearing:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

examples/extended_vfs/gpio/gpio_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/extended_vfs/i2c/i2c_bh1750:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/extended_vfs/i2c/i2c_tt21100:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/extended_vfs/ledc/ledc_simple:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/extended_vfs/spi/spi_master_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/extended_vfs/spi/spi_slave_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/get-started/blink:
  enable:
    - if: (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4) and IDF_TARGET in ["esp32","esp32s2","esp32s3"]

examples/get-started/button_power_save:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/get-started/knob_power_save:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/sensors/power_measure:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/hmi/perf_benchmark:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s3","esp32c3"]

examples/indicator:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/keyboard:
  enable:
    - if: IDF_TARGET == "esp32s3"

examples/indicator/ws2812_strips:
  enable:
    - if: SOC_RMT_SUPPORTED == 1

examples/lighting/lightbulb:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/motor/foc_openloop_control:
  enable:
    - if: IDF_TARGET == "esp32s3"

examples/motor/foc_openloop_control:
  disable:
    - if: IDF_TARGET == "esp32c2"

examples/motor/foc_velocity_control:
  disable:
    - if: IDF_TARGET == "esp32c2"

examples/motor/foc_knob_example:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s3"]

examples/motor/servo_control:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/ota/simple_ota_example:
  enable:
    - if: IDF_TARGET in ["esp32c2","esp32c3","esp32"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
    - if: IDF_TARGET in ["esp32c2","esp32c3","esp32","esp32c6"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 1)

examples/screen:
  enable:
    - if: IDF_TARGET == "esp32" and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)

examples/sensors/sensor_control_led:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)

examples/sensors/sensor_hub_monitor:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)

examples/usb/device/usb_dongle:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

examples/touch/touch_proximity:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

examples/ulp/lp_cpu/lp_environment_sensor:
  enable:
    - if: IDF_TARGET in ["esp32c6"]

examples/usb/device/usb_uart_bridge:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32s2"]

examples/usb/device/usb_uac:
  enable:
    - if: IDF_TARGET in ["esp32s3"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)

examples/usb/device/usb_dual_uvc_device:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32s2"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_webcam:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32s2"]

examples/usb/device/usb_extend_screen:
  enable:
    - if: IDF_TARGET in ["esp32p4"]

examples/usb/device/usb_hid_device:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_lcd_display:
  enable:
    - if: IDF_TARGET in ["esp32p4"]

examples/usb/device/usb_msc_wireless_disk:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0)
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_surface_dial:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_uf2_nvs:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_uf2_ota:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/host/usb_camera_lcd_display:
  enable:
    - if: IDF_TARGET == "esp32s3" and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 0)

examples/usb/host/usb_camera_mic_spk:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/host/usb_audio_player:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/usb/host/usb_cdc_4g_module:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/usb/host/usb_cdc_basic:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/usb/host/usb_msc_ota:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/otg/usb_host_device_mode_manual_switch:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

examples/utilities/xz_decompress_file:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/gprof/gprof_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/elf_loader/elf_loader_example:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
    - if: IDF_TARGET in ["esp32c6"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)

examples/elf_loader/build_elf_file_example:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
    - if: IDF_TARGET in ["esp32c6"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)
