# Note: All operators are binary operators. For more than two operands, you may use the nested parentheses trick.
# For example:
#    *  A == 1 or (B == 2 and C in [1,2,3])
#    *  (A == 1 and B == 2) or (C not in ["3", "4", 5])

examples/ai/esp_dl/human_activity_recognition:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 3)

examples/ai/esp_dl/touchpad_digit_recognition:
  enable:
    - if: IDF_TARGET in ["esp32s3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 3)

examples/audio/wav_player:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/bluetooth/ble_conn_mgr/ble_periodic_adv:
  enable:
    - if: SOC_BLE_50_SUPPORTED == 1

examples/bluetooth/ble_conn_mgr/ble_periodic_sync:
  enable:
    - if: SOC_BLE_50_SUPPORTED == 1

examples/bluetooth/ble_conn_mgr/ble_spp/spp_client:
  enable:
    - if: SOC_BLE_SUPPORTED == 1
examples/bluetooth/ble_conn_mgr/ble_spp/spp_server:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_profiles/ble_anp:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_profiles/ble_hrp:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_profiles/ble_htp:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_profiles/ble_midi:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_ans:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_bas:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_bcs:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_cts:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_dis:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_hrs:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_hts:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_tps:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_uds:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_services/ble_wss:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_ota:
  enable:
    # - if: SOC_BLE_SUPPORTED == 1
    # The ble_ota component has not yet been tested on ESP32-C5 and ESP32-C61,
    # so the component is not currently marked as supporting these targets.
    - if: IDF_TARGET in ["esp32", "esp32c3", "esp32h2", "esp32s3", "esp32c2", "esp32c6"]

examples/bluetooth/ble_remote_control:
  enable:
    - if: SOC_BLE_SUPPORTED == 1

examples/bluetooth/ble_adv/bthome/dimmer:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/bluetooth/ble_adv/bthome/bulb:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/mcp/mcp_server:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3","esp32c6"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 4)
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3","esp32c6"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/camera/basic:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/camera/pic_server:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/camera/test_framerate:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/camera/video_recorder:
  enable:
    - if: IDF_TARGET == "esp32s3"

examples/camera/video_stream_server:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/display/lcd/hdmi_video_renderer:
  enable:
    - if: IDF_TARGET in ["esp32p4"]

examples/display/lcd/lcd_layer_blending:
  enable:
    - if: IDF_TARGET in ["esp32p4"]

examples/display/lcd/mipi_dsi_avoid_tearing:
  enable:
    - if: IDF_TARGET in ["esp32p4"]

examples/display/lcd/qspi_with_ram:
  enable:
    - if: IDF_TARGET in ["esp32s3", "esp32p4", "esp32c3", "esp32c5", "esp32c6"]

examples/display/lcd/qspi_without_ram:
  enable:
    - if: IDF_TARGET in ["esp32s3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 3)

examples/display/lcd/rgb_lcd_8bit:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

examples/display/lcd/rgb_avoid_tearing:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

examples/display/gui/lvgl_common_demo:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/display/gui/lvgl_decode_image:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/display/gui/lvgl_dummy_draw:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/display/gui/lvgl_freetype_font:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/display/gui/lvgl_multi_screen:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/display/gui/lvgl_light_sleep_demo:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4","esp32c3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/display/gui/lvgl_eaf_player:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)

examples/extended_vfs/gpio/gpio_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/extended_vfs/i2c/i2c_bh1750:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/extended_vfs/i2c/i2c_tt21100:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/extended_vfs/ledc/ledc_simple:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/extended_vfs/spi/spi_master_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/extended_vfs/spi/spi_slave_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/get-started/blink:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3"]

examples/get-started/button_power_save:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/get-started/knob_power_save:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/sensors/power_measure:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/indicator:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/keyboard:
  enable:
    - if: IDF_TARGET == "esp32s3"

examples/indicator/ws2812_strips:
  enable:
    - if: SOC_RMT_SUPPORTED == 1

examples/lighting/lightbulb:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/motor/foc_openloop_control:
  enable:
    - if: IDF_TARGET == "esp32s3"
  disable:
    - if: IDF_TARGET == "esp32c2"

examples/motor/foc_velocity_control:
  enable:
    - if: IDF_TARGET == "esp32s3"

examples/motor/foc_knob_example:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s3"]

examples/motor/servo_control:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/ota/simple_ota_example:
  enable:
    - if: IDF_TARGET in ["esp32c2", "esp32c3", "esp32c5", "esp32c6", "esp32c61", "esp32", "esp32s3", "esp32h2"]

examples/sensors/sensor_control_led:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2"] and (IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR == 4)

examples/sensors/sensor_hub_monitor:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2"]

examples/usb/device/bootloader_uf2:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1
  disable:
    - if: IDF_TARGET in ["esp32s2"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR < 3)
      temporary: true
      reason: ESP32-S2 may encounter toolchain errors when using IDF versions below 5.3.
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)
      temporary: true
      reason: "see AEG-2895 for more details"

examples/usb/device/usb_dongle:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 5)

examples/touch/touch_button:
  enable:
    - if: SOC_TOUCH_SENSOR_SUPPORTED == 1

examples/touch/touch_button_sensor:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s2", "esp32s3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR < 4)
    - if: IDF_TARGET in ["esp32", "esp32s2", "esp32s3", "esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 4)

examples/touch/touch_proximity:
  enable:
    - if: IDF_TARGET in ["esp32s3"]

examples/touch/touch_slider_sensor:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s2", "esp32s3"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR < 4)
    - if: IDF_TARGET in ["esp32", "esp32s2", "esp32s3", "esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 4)

examples/ulp/lp_cpu/lp_environment_sensor:
  enable:
    - if: IDF_TARGET in ["esp32c6"]

examples/usb/device/usb_uart_bridge:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32s2"]

examples/usb/device/usb_uac:
  enable:
    - if: IDF_TARGET in ["esp32s3"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)

examples/usb/device/usb_dual_uvc_device:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32s2"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_webcam:
  enable:
    - if: IDF_TARGET in ["esp32s3","esp32s2"]

examples/usb/device/usb_extend_screen:
  enable:
    - if: IDF_TARGET in ["esp32p4"]

examples/usb/device/usb_hid_device:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_lcd_display:
  enable:
    - if: IDF_TARGET in ["esp32p4"]

examples/usb/device/usb_msc_wireless_disk:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_surface_dial:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_uf2_nvs:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/device/usb_uf2_ota:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/host/usb_camera_lcd_display:
  enable:
    - if: IDF_TARGET == "esp32s3" and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 0)

examples/usb/host/usb_camera_mic_spk:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/host/usb_audio_player:
  enable:
    - if: IDF_TARGET in ["esp32s2","esp32s3"]

examples/usb/host/usb_cdc_4g_module:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

examples/usb/host/usb_cdc_basic:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

examples/usb/host/usb_host_msc_example:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1
  disable:
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 5)
      temporary: true
      reason: "see AEG-2895 for more details"

examples/usb/host/usb_hub_dual_camera:
  enable:
    - if: IDF_TARGET in ["esp32s2", "esp32s3","esp32p4"]

examples/usb/host/usb_ecm_4g_module:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

examples/usb/host/usb_msc_ota:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1
  disable:
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR == 0
      temporary: true
      reason: esp32-s3-usb-otg not supported idf release 5.0 build yet

examples/usb/host/usb_rndis_4g_module:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

examples/usb/otg/usb_host_device_mode_manual_switch:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

examples/utilities/xz_decompress_file:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/utilities/adc_tp_calibration:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 0)

examples/vision/opencv/color_tracker:
  enable:
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 4)

examples/gprof/gprof_simple:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3","esp32c3"]

examples/elf_loader/elf_loader_example:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
    - if: IDF_TARGET in ["esp32c6"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)
    - if: IDF_TARGET in ["esp32c61"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5 and IDF_VERSION_PATCH >= 1)

examples/elf_loader/build_elf_file_example:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
    - if: IDF_TARGET in ["esp32c6"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)
    - if: IDF_TARGET in ["esp32c61"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5 and IDF_VERSION_PATCH >= 1)

examples/elf_loader/elf_embed_example:
  enable:
    - if: IDF_TARGET in ["esp32","esp32s2","esp32s3"]
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
    - if: IDF_TARGET in ["esp32c6"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 1)
    - if: IDF_TARGET in ["esp32c61"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5 and IDF_VERSION_PATCH >= 1)

examples/relinker:
  enable:
    - if: IDF_TARGET in ["esp32c2","esp32c3"]

examples/robot/ragtime_panthera/follower:
  enable:
    - if: IDF_TARGET in ["esp32p4"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)

examples/robot/ragtime_panthera/follower/receiver:
  enable:
    - if: IDF_TARGET in ["esp32c6"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)

examples/robot/ragtime_panthera/leader:
  enable:
    - if: IDF_TARGET in ["esp32c3"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)
