/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: rgb8888

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenRGB8888
void ui_ScreenRGB8888_screen_init(void);
lv_obj_t * ui_ScreenRGB8888;
lv_obj_t * ui_ImageRGB8888;
lv_obj_t * ui_LabelRGB8888;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_ScreenRGB565
void ui_ScreenRGB565_screen_init(void);
lv_obj_t * ui_ScreenRGB565;
lv_obj_t * ui_LabelRGB565;

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    ui_ScreenRGB8888_screen_init();
    ui_ScreenRGB565_screen_init();

    lv_disp_load_scr(ui_ScreenRGB8888);
}
