/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: rgb8888

#ifndef _RGB8888_UI_H
#define _RGB8888_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenRGB8888
void ui_ScreenRGB8888_screen_init(void);
extern lv_obj_t * ui_ScreenRGB8888;
extern lv_obj_t * ui_ImageRGB8888;
extern lv_obj_t * ui_LabelRGB8888;
extern lv_obj_t * ui____initial_actions0;

// SCREEN: ui_ScreenRGB565
void ui_ScreenRGB565_screen_init(void);
extern lv_obj_t * ui_ScreenRGB565;
extern lv_obj_t * ui_LabelRGB565;

LV_IMG_DECLARE(ui_img_espressif_qrcode_png_small);    // assets/ui_img_espressif_qrcode_png_small.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
