/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_QOI_FILES           2
#define MMAP_QOI_CHECKSUM        0xE594

enum MMAP_QOI_LISTS {
    MMAP_QOI_RED_JPG_QOI = 0,        /*!< red_jpg.qoi */
    MMAP_QOI_RED_PNG_QOI = 1,        /*!< red_png.qoi */
};
