/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SPNG_FILES           1
#define MMAP_SPNG_CHECKSUM        0x8885

enum MMAP_SPNG_LISTS {
    MMAP_SPNG_RED_PNG_SPNG = 0,        /*!< red_png.spng */
};
