/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SJPG_FILES           1
#define MMAP_SJPG_CHECKSUM        0x2F50

enum MMAP_SJPG_LISTS {
    MMAP_SJPG_RED_JPG_SJPG = 0,        /*!< red_jpg.sjpg */
};
