/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_PJPG_FILES           1
#define MMAP_PJPG_CHECKSUM        0x1350

enum MMAP_PJPG_LISTS {
    MMAP_PJPG_RED_PNG_PJPG = 0,        /*!< red_png.pjpg */
};
