#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := lowpower_evb_demo

EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/wifi/wifi_conn
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/wifi/smart_config
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/network/tcp
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/led
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/button
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/general/param
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/spi_devices/epaper
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/i2c_devices/i2c_bus
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/i2c_devices/sensor/hts221
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/i2c_devices/sensor/bh1750
EXTRA_COMPONENT_DIRS += $(IOT_SOLUTION_PATH)/components/framework/lowpower_framework

include $(IDF_PATH)/make/project.mk