/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define TOTAL_MMAP_FILES      1
#define MMAP_CHECKSUM         0x97DD

enum MMAP_FILES {
    MMAP_DEJAVUSANS_TTF = 0,   /*!< DejaVuSans.ttf */
};
