/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_IMAGES_FILES           2
#define MMAP_IMAGES_CHECKSUM        0x9F8C

enum MMAP_IMAGES_LISTS {
    MMAP_IMAGES_RED_JPG_JPG = 0,        /*!< red_jpg.jpg */
    MMAP_IMAGES_RED_PNG_PNG = 1,        /*!< red_png.png */
};
