/*
  * ESPRESSIF MIT License
  *
  * Copyright (c) 2017 <ESPRESSIF SYSTEMS (SHANGHAI) PTE LTD>
  *
  * Permission is hereby granted for use on ESPRESSIF SYSTEMS products only, in which case,
  * it is free of charge, to any person obtaining a copy of this software and associated
  * documentation files (the "Software"), to deal in the Software without restriction, including
  * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
  * and/or sell copies of the Software, and to permit persons to whom the Software is furnished
  * to do so, subject to the following conditions:
  *
  * The above copyright notice and this permission notice shall be included in all copies or
  * substantial portions of the Software.
  *
  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
  *
  */

#ifndef _IOT_SOCKET_CONFIG_H_
#define _IOT_SOCKET_CONFIG_H_
#include "sdkconfig.h"
#include "driver/gpio.h"

#if CONFIG_SMART_SOCKET_DEVICE
#define SOCKET_NAME_SPACE                       CONFIG_SMART_SOCKET_NAME_SPACE
#define SOCKET_PARAM_KEY                        CONFIG_SMART_SOCKET_PARAM_KEY
#define SOCKET_POWER_METER_ENABLE               CONFIG_SMART_SOCKET_POWER_METER_ENABLE
#define PM_CF_IO_NUM                            CONFIG_SMART_SOCKET_PM_CF_IO
#define PM_CFI_IO_NUM                           CONFIG_SMART_SOCKET_PM_CFI_IO
#define PM_POWER_PARAM                          CONFIG_SMART_SOCKET_PM_POWER_COEF
#define PM_CURRENT_PARAM                        CONFIG_SMART_SOCKET_PM_CURRENT_COEF
#define PM_VOLTAGE_PARAM                        CONFIG_SMART_SOCKET_PM_VOLTAGE_COEF
#define BUTTON_IO_NUM_MAIN                      CONFIG_SMART_SOCKET_MAIN_BUTTON_IO
#define BUTTON_ACTIVE_LEVEL                     CONFIG_SMART_SOCKET_MAIN_BUTTON_ACT_LEVEL
#define NET_LED_NUM                             CONFIG_SMART_SOCKET_NET_STATUS_LED_IO
#define LED_DARK_LEVEL                          CONFIG_SMART_SOCKET_NET_STATUS_LED_OFF_LEVEL
#define SOCKET_UNIT_NUM                         CONFIG_SMART_SOCKET_UNIT_NUM

#define SMART_SOCKET_UNIT0_BUTTON_IO            CONFIG_SMART_SOCKET_UNIT0_BUTTON_IO
#define SMART_SOCKET_UNIT0_BUTTON_ACTIVE_LEVEL  CONFIG_SMART_SOCKET_UNIT0_BUTTON_ACTIVE_LEVEL
#define SMART_SOCKET_UNIT0_LED_IO               CONFIG_SMART_SOCKET_UNIT0_LED_IO
#define SMART_SOCKET_UNIT0_LED_OFF_LEVEL        CONFIG_SMART_SOCKET_UNIT0_LED_OFF_LEVEL
#define SMART_SOCKET_UNIT0_RELAY_OFF_LEVEL      CONFIG_SMART_SOCKET_UNIT0_RELAY_OFF_LEVEL
#define SMART_SOCKET_UNIT0_RELAY_CTRL_MODE      CONFIG_SMART_SOCKET_UNIT0_RELAY_CTRL_MODE
#define SMART_SOCKET_UNIT0_RELAY_IO_MODE        CONFIG_SMART_SOCKET_UNIT0_RELAY_IO_MODE
#define SMART_SOCKET_UNIT0_RELAY_CTL_IO         CONFIG_SMART_SOCKET_UNIT0_RELAY_CTL_IO
#define SMART_SOCKET_UNIT0_RELAY_CLK_IO         CONFIG_SMART_SOCKET_UNIT0_RELAY_CLK_IO
#if SOCKET_UNIT_NUM > 1
#define SMART_SOCKET_UNIT1_BUTTON_IO            CONFIG_SMART_SOCKET_UNIT1_BUTTON_IO
#define SMART_SOCKET_UNIT1_BUTTON_ACTIVE_LEVEL  CONFIG_SMART_SOCKET_UNIT1_BUTTON_ACTIVE_LEVEL
#define SMART_SOCKET_UNIT1_LED_IO               CONFIG_SMART_SOCKET_UNIT1_LED_IO
#define SMART_SOCKET_UNIT1_LED_OFF_LEVEL        CONFIG_SMART_SOCKET_UNIT1_LED_OFF_LEVEL
#define SMART_SOCKET_UNIT1_RELAY_OFF_LEVEL      CONFIG_SMART_SOCKET_UNIT1_RELAY_OFF_LEVEL
#define SMART_SOCKET_UNIT1_RELAY_CTRL_MODE      CONFIG_SMART_SOCKET_UNIT1_RELAY_CTRL_MODE
#define SMART_SOCKET_UNIT1_RELAY_IO_MODE        CONFIG_SMART_SOCKET_UNIT1_RELAY_IO_MODE
#define SMART_SOCKET_UNIT1_RELAY_CTL_IO         CONFIG_SMART_SOCKET_UNIT1_RELAY_CTL_IO
#define SMART_SOCKET_UNIT1_RELAY_CLK_IO         CONFIG_SMART_SOCKET_UNIT1_RELAY_CLK_IO
#endif
#if SOCKET_UNIT_NUM > 2
#define SMART_SOCKET_UNIT2_BUTTON_IO            CONFIG_SMART_SOCKET_UNIT2_BUTTON_IO
#define SMART_SOCKET_UNIT2_BUTTON_ACTIVE_LEVEL  CONFIG_SMART_SOCKET_UNIT2_BUTTON_ACTIVE_LEVEL
#define SMART_SOCKET_UNIT2_LED_IO               CONFIG_SMART_SOCKET_UNIT2_LED_IO
#define SMART_SOCKET_UNIT2_LED_OFF_LEVEL        CONFIG_SMART_SOCKET_UNIT2_LED_OFF_LEVEL
#define SMART_SOCKET_UNIT2_RELAY_OFF_LEVEL      CONFIG_SMART_SOCKET_UNIT2_RELAY_OFF_LEVEL
#define SMART_SOCKET_UNIT2_RELAY_CTRL_MODE      CONFIG_SMART_SOCKET_UNIT2_RELAY_CTRL_MODE
#define SMART_SOCKET_UNIT2_RELAY_IO_MODE        CONFIG_SMART_SOCKET_UNIT2_RELAY_IO_MODE
#define SMART_SOCKET_UNIT2_RELAY_CTL_IO         CONFIG_SMART_SOCKET_UNIT2_RELAY_CTL_IO
#define SMART_SOCKET_UNIT2_RELAY_CLK_IO         CONFIG_SMART_SOCKET_UNIT2_RELAY_CLK_IO
#endif
#if SOCKET_UNIT_NUM > 3
#define SMART_SOCKET_UNIT3_BUTTON_IO            CONFIG_SMART_SOCKET_UNIT3_BUTTON_IO
#define SMART_SOCKET_UNIT3_BUTTON_ACTIVE_LEVEL  CONFIG_SMART_SOCKET_UNIT3_BUTTON_ACTIVE_LEVEL
#define SMART_SOCKET_UNIT3_LED_IO               CONFIG_SMART_SOCKET_UNIT3_LED_IO
#define SMART_SOCKET_UNIT3_LED_OFF_LEVEL        CONFIG_SMART_SOCKET_UNIT3_LED_OFF_LEVEL
#define SMART_SOCKET_UNIT3_RELAY_OFF_LEVEL      CONFIG_SMART_SOCKET_UNIT3_RELAY_OFF_LEVEL
#define SMART_SOCKET_UNIT3_RELAY_CTRL_MODE      CONFIG_SMART_SOCKET_UNIT3_RELAY_CTRL_MODE
#define SMART_SOCKET_UNIT3_RELAY_IO_MODE        CONFIG_SMART_SOCKET_UNIT3_RELAY_IO_MODE
#define SMART_SOCKET_UNIT3_RELAY_CTL_IO         CONFIG_SMART_SOCKET_UNIT3_RELAY_CTL_IO
#define SMART_SOCKET_UNIT3_RELAY_CLK_IO         CONFIG_SMART_SOCKET_UNIT3_RELAY_CLK_IO
#endif

#else
#define SOCKET_NAME_SPACE                       "socket"
#define SOCKET_PARAM_KEY                        "socket_param"
#define SOCKET_POWER_METER_ENABLE               (1)
#define PM_CF_IO_NUM                            (25)
#define PM_CFI_IO_NUM                           (26)
#define PM_POWER_PARAM                          (1293699)
#define PM_CURRENT_PARAM                        (13670)
#define PM_VOLTAGE_PARAM                        (102961)
#define BUTTON_IO_NUM_MAIN                      (4)
#define BUTTON_ACTIVE_LEVEL                     (0)
#define NET_LED_NUM                             GPIO_NUM_19
#define SOCKET_UNIT_NUM                         (2)
#define LED_DARK_LEVEL                          LED_DARK_LOW
#if SOCKET_UNIT_NUM > 0
#define SMART_SOCKET_UNIT0_BUTTON_IO            (5)
#define SMART_SOCKET_UNIT0_BUTTON_ACTIVE_LEVEL  (0)
#define SMART_SOCKET_UNIT0_LED_IO               (17)
#define SMART_SOCKET_UNIT0_LED_OFF_LEVEL        (0)
#define SMART_SOCKET_UNIT0_RELAY_OFF_LEVEL      (1)
#define SMART_SOCKET_UNIT0_RELAY_CTRL_MODE      (1)
#define SMART_SOCKET_UNIT0_RELAY_IO_MODE        (0)
#define SMART_SOCKET_UNIT0_RELAY_CTL_IO         (12)
#define SMART_SOCKET_UNIT0_RELAY_CLK_IO         (-1)
#endif
#if SOCKET_UNIT_NUM > 1
#define SMART_SOCKET_UNIT1_BUTTON_IO            (2)
#define SMART_SOCKET_UNIT1_BUTTON_ACTIVE_LEVEL  (0)
#define SMART_SOCKET_UNIT1_LED_IO               (18)
#define SMART_SOCKET_UNIT1_LED_OFF_LEVEL        (0)
#define SMART_SOCKET_UNIT1_RELAY_OFF_LEVEL      (1)
#define SMART_SOCKET_UNIT1_RELAY_CTRL_MODE      (1)
#define SMART_SOCKET_UNIT1_RELAY_IO_MODE        (0)
#define SMART_SOCKET_UNIT1_RELAY_CTL_IO         (13)
#define SMART_SOCKET_UNIT1_RELAY_CLK_IO         (-1)
#endif
#if SOCKET_UNIT_NUM > 2
#define SMART_SOCKET_UNIT2_BUTTON_IO            (20)
#define SMART_SOCKET_UNIT2_BUTTON_ACTIVE_LEVEL  (0)
#define SMART_SOCKET_UNIT2_LED_IO               (21)
#define SMART_SOCKET_UNIT2_LED_OFF_LEVEL        (0)
#define SMART_SOCKET_UNIT2_RELAY_OFF_LEVEL      (1)
#define SMART_SOCKET_UNIT2_RELAY_CTRL_MODE      (1)
#define SMART_SOCKET_UNIT2_RELAY_IO_MODE        (0)
#define SMART_SOCKET_UNIT2_RELAY_CTL_IO         (22)
#define SMART_SOCKET_UNIT2_RELAY_CLK_IO         (-1)
#endif
#if SOCKET_UNIT_NUM > 3
#define SMART_SOCKET_UNIT3_BUTTON_IO            (23)
#define SMART_SOCKET_UNIT3_BUTTON_ACTIVE_LEVEL  (0)
#define SMART_SOCKET_UNIT3_LED_IO               (24)
#define SMART_SOCKET_UNIT3_LED_OFF_LEVEL        (0)
#define SMART_SOCKET_UNIT3_RELAY_OFF_LEVEL      (1)
#define SMART_SOCKET_UNIT3_RELAY_CTRL_MODE      (1)
#define SMART_SOCKET_UNIT3_RELAY_IO_MODE        (0)
#define SMART_SOCKET_UNIT3_RELAY_CTL_IO         (27)
#define SMART_SOCKET_UNIT3_RELAY_CLK_IO         (-1)
#endif
#endif


#endif
